language: node_js
node_js:
  - "4.2.0"
services:
  - mongodb
before_script:
  - npm install -g bower
  - bower install
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  # - sh -e /etc/init.d/xvfb start
